kind: pipeline
name: GUISSH
steps:
- name: Deploy Mac App
  image: appleboy/drone-ssh
  environment:
    MAC_USER_PASS:
      from_secret: password
  settings:
    host:
      from_secret: host
    username:
      from_secret: username
    ssh_key:
      from_secret: ssh_key
    port: 22
    command_timeout: 1000s
    envs: [MAC_USER_PASS]
    script:
      - cd ~/Documents/dev/blockdrei/guissh
      # current version
      - VERSION=$(head package.json | grep version | awk '{print $2}' | cut -d\" -f2)
      # pull new
      # todo other branches than beta (git pull here pulls origin/beta automatically)
      - git stash
      - git pull
      - VERSION_NEW=$(head package.json | grep version | awk '{print $2}' | cut -d\" -f2)
      # set path so we can use commands
      - PATH=/usr/local/bin:/bin:/usr/bin
      # unlock keychain for codesigning
      - security unlock-keychain -p $MAC_USER_PASS login.keychain
      - npm install
      - if [ $VERSION != $VERSION_NEW ]; then npm run build-upload else echo "Version still the same. Do not build."; fi
---
kind: secret
name: username
get:
  path: blockdrei/mac-build-01
  name: username
---
kind: secret
name: password
get:
  path: blockdrei/mac-build-01
  name: password
---
kind: secret
name: ssh_key
get:
  path: blockdrei/mac-build-01
  name: privateKey
---
kind: secret
name: host
get:
  path: blockdrei/mac-build-01
  name: host